//defining endpoints here


GET http://localhost:5013/


###


POST http://localhost:5013/api/token/authenticate
Content-Type: application/json

{
    "email": "JohnDoe123@gmail.com",
    "password": "Verysecurepassword123"
}

###

POST http://localhost:5013/api/ApplicationUsers
Content-Type: application/json

{
    "Email": "",
    "FirstName": "",
    "LastName": "",
    "PasswordHash": "",
    "PasswordSalt": "",

}

###
DELETE http://localhost:5013/api/ApplicationUser

###

POST http://localhost:5013/api/Videos
Content-Type: application/json

{
    "VideoUrl":"",
    "Title":"",
    "Broadcaster":"",
}

###
GET http://localhost:5013/api/Videos